stages:
  - build
  - test
  - deploy_develop
  - deploy_production
build:
    stage: build
    tags:
     - ugrad
    script:
     - echo "Build stage"
     - mvn compile
test:
    stage: test
    tags:
     - ugrad
    script:
     - echo "Test stage"
     - mvn test
    artifacts:
      when: always
      reports:
        junit:
          - $CI_PROJECT_DIR/target/surefire-reports/TEST-*.xml
          - $CI_PROJECT_DIR/target/failsafe-reports/TEST-*.xml
deploy_develop:
  stage: deploy_develop
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_NAME_DEV  --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy_production:
  stage: deploy_production
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_NAME_PROD  --api-key=$HEROKU_API_KEY
  only:
    - master
    - release-1

   
